title: Roseline Olory
logo: /Image/PhotoRoseline.jpg
description: On this personal website, you will find information about me and my research.
google_analytics:
theme: jekyll-theme-minimal
email: oloryroseline@gmail.com
author: Roseline Olory
